# roles/setup/tasks/main.yml
---

- name: Setup network
  include_tasks: network.yml

- name: Setup ssh between nodes
  include_tasks: ssh.yml

- name: Disable bluetooth
  include_tasks: bluetooth.yml
